ANALYTICAL FOUNDATION

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('accepted_2007_to_2018Q4.csv', nrows=100000, low_memory=False)
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df['id'].isnull().sum() == 0

True

In [17]:
df['id'].is_unique

True

In [18]:
#low_memory=False -> using low_memory = False so pandas correctly figures out column data types at once, avoiding data type mix-ups.

In [19]:
df.shape

(100000, 151)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 151 entries, id to settlement_term
dtypes: float64(114), int64(1), object(36)
memory usage: 115.2+ MB

In [21]:
df.columns.tolist()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [22]:
df[['loan_amnt', 'annual_inc', 'loan_status', 'int_rate']].head()

   loan_amnt  annual_inc loan_status  int_rate
0     3600.0     55000.0  Fully Paid     13.99
1    24700.0     65000.0  Fully Paid     11.99
2    20000.0     63000.0  Fully Paid     10.78
3    35000.0    110000.0     Current     14.85
4    10400.0    104433.0  Fully Paid     22.45

In [23]:
df[['loan_amnt', 'annual_inc', 'loan_status', 'int_rate']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   loan_amnt    100000 non-null  float64
 1   annual_inc   100000 non-null  float64
 2   loan_status  100000 non-null  object
 3   int_rate     100000 non-null  float64
dtypes: float64(3), object(1)
memory usage: 3.1+ MB

In [24]:
df['loan_status'].value_counts()

loan_status
Fully Paid            70288
Charged Off           17603
Current               11402
Late (31-120 days)      441
In Grace Period         199
Late (16-30 days)        66
Default                   1
Name: count, dtype: int64

In [25]:
 df[['loan_amnt', 'annual_inc', 'int_rate']].describe()

           loan_amnt    annual_inc       int_rate
count  100000.000000  1.000000e+05  100000.000000
mean    15055.861000  7.837135e+04      12.200478
std      8641.837441  8.929612e+04       4.137499
min      1000.000000  0.000000e+00       5.320000
25%      8000.000000  4.760000e+04       9.170000
50%     13875.000000  6.500000e+04      11.990000
75%     20000.000000  9.400000e+04      14.480000
max     35000.000000  9.000000e+06      28.990000

In [26]:
df.isnull().sum().sort_values(ascending=False).head(20)

sec_app_open_act_il                           100000
member_id                                     100000
revol_bal_joint                               100000
sec_app_fico_range_low                        100000
sec_app_fico_range_high                       100000
sec_app_earliest_cr_line                      100000
sec_app_inq_last_6mths                        100000
sec_app_mort_acc                              100000
sec_app_open_acc                              100000
sec_app_revol_util                            100000
sec_app_num_rev_accts                         100000
sec_app_chargeoff_within_12_mths              100000
sec_app_collections_12_mths_ex_med            100000
sec_app_mths_since_last_major_derog           100000
desc                                           99993
dti_joint                                      99500
verification_status_joint                      99498
annual_inc_joint                               99498
orig_projected_additional_accrued_interest     99379
hardship_amount                                99219
dtype: int64

In [27]:
selected_cols = ['id',
    'loan_amnt',
    'term',
    'int_rate',
    'installment',
    'grade',
    'sub_grade',
    'annual_inc',
    'loan_status',
    'dti',
    'fico_range_low',
    'fico_range_high',
    'revol_util',
    'pub_rec_bankruptcies',
    'purpose',
    'addr_state'
]

df_clean = df[selected_cols]

df_clean.head()

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,annual_inc,loan_status,dti,fico_range_low,fico_range_high,revol_util,pub_rec_bankruptcies,purpose,addr_state
0,68407277,3600.0,36 months,13.99,123.03,C,C4,55000.0,Fully Paid,5.91,675.0,679.0,29.7,0.0,debt_consolidation,PA
1,68355089,24700.0,36 months,11.99,820.28,C,C1,65000.0,Fully Paid,16.06,715.0,719.0,19.2,0.0,small_business,SD
2,68341763,20000.0,60 months,10.78,432.66,B,B4,63000.0,Fully Paid,10.78,695.0,699.0,56.2,0.0,home_improvement,IL
3,66310712,35000.0,60 months,14.85,829.90,C,C5,110000.0,Current,17.06,785.0,789.0,11.6,0.0,debt_consolidation,NJ
4,68476807,10400.0,60 months,22.45,289.91,F,F1,104433.0,Fully Paid,25.37,695.0,699.0,64.5,0.0,major_purchase,PA

In [28]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    100000 non-null  int64
 1   loan_amnt             100000 non-null  float64
 2   term                  100000 non-null  object
 3   int_rate              100000 non-null  float64
 4   installment           100000 non-null  float64
 5   grade                 100000 non-null  object
 6   sub_grade             100000 non-null  object
 7   annual_inc            100000 non-null  float64
 8   loan_status           100000 non-null  object
 9   dti                   99998 non-null   float64
 10  fico_range_low        100000 non-null  float64
 11  fico_range_high       100000 non-null  float64
 12  revol_util            99963 non-null   float64
 13  pub_rec_bankruptcies  100000 non-null  float64
 14  purpose               100000 non-null  object
 15  addr_state            100000 non-null  object
dtypes: float64(9), int64(1), object(6)
memory usage: 12.2+ MB

In [29]:
df_clean = df_clean.dropna()

In [30]:
df_clean.shape

(99961, 16)

In [31]:
df_clean['loan_status'].value_counts(normalize=True) * 100     #percentage distribution , checking portfolio health

loan_status
Fully Paid            70.286412
Charged Off           17.600864
Current               11.405448
Late (31-120 days)     0.441172
In Grace Period        0.199078
Late (16-30 days)      0.066026
Default                0.001000
Name: proportion, dtype: float64

In [32]:
baseline = 12
df_clean.loc[:,'utilization_diff'] = df_clean['revol_util'] - baseline

In [33]:
df_clean.head()

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,annual_inc,loan_status,dti,fico_range_low,fico_range_high,revol_util,pub_rec_bankruptcies,purpose,addr_state,utilization_diff
0,68407277,3600.0,36 months,13.99,123.03,C,C4,55000.0,Fully Paid,5.91,675.0,679.0,29.7,0.0,debt_consolidation,PA,17.7
1,68355089,24700.0,36 months,11.99,820.28,C,C1,65000.0,Fully Paid,16.06,715.0,719.0,19.2,0.0,small_business,SD,7.2
2,68341763,20000.0,60 months,10.78,432.66,B,B4,63000.0,Fully Paid,10.78,695.0,699.0,56.2,0.0,home_improvement,IL,44.2
3,66310712,35000.0,60 months,14.85,829.90,C,C5,110000.0,Current,17.06,785.0,789.0,11.6,0.0,debt_consolidation,NJ,-0.4
4,68476807,10400.0,60 months,22.45,289.91,F,F1,104433.0,Fully Paid,25.37,695.0,699.0,64.5,0.0,major_purchase,PA,52.5

In [34]:
df_clean[['revol_util', 'utilization_diff']].head()

   revol_util  utilization_diff
0        29.7              17.7
1        19.2               7.2
2        56.2              44.2
3        11.6              -0.4
4        64.5              52.5

In [35]:
df_clean.loc[:, 'high_util_risk'] = df_clean['utilization_diff'].apply(lambda x: 1 if x > 30 else 0)

In [36]:
df_clean['high_util_risk'].value_counts()

high_util_risk
1    64597
0    35364
Name: count, dtype: int64

In [37]:
df_clean[['revol_util', 'utilization_diff', 'high_util_risk']].head(10)

   revol_util  utilization_diff  high_util_risk
0        29.7              17.7               0
1        19.2               7.2               0
2        56.2              44.2               1
3        11.6              -0.4               0
4        64.5              52.5               1
5        68.4              56.4               1
6        84.5              72.5               1
7         5.7              -6.3               0
8        34.5              22.5               0
9        39.1              27.1               0

In [38]:
df_clean.groupby('high_util_risk')['loan_status'].value_counts() #raw counts

high_util_risk  loan_status
0               Fully Paid            26691
                Charged Off            5677
                Current                2796
                Late (31-120 days)      125
                In Grace Period          50
                Late (16-30 days)        25
1               Fully Paid            43568
                Charged Off           11917
                Current                8605
                Late (31-120 days)      316
                In Grace Period         149
                Late (16-30 days)        41
                Default                   1
Name: count, dtype: int64

In [39]:
pd.crosstab(df_clean['high_util_risk'],df_clean['loan_status'],normalize='index') * 100     #standardized risk comparison, percentages.

loan_status,Charged Off,Current,Default,Fully Paid,In Grace Period,Late (16-30 days),Late (31-120 days)
high_util_risk,,,,,,,
0,16.053048,7.906345,0.000000,75.475059,0.141387,0.070693,0.353467
1,18.448225,13.321052,0.001548,67.445857,0.230661,0.063470,0.489187

In [40]:
df_clean.loc[:, 'high_dti_risk'] = df_clean['dti'].apply(lambda x: 1 if x > 20 else 0)

In [41]:
df_clean['high_dti_risk'].value_counts()

high_dti_risk
0    55273
1    44688
Name: count, dtype: int64

In [42]:
pd.crosstab(df_clean['high_dti_risk'],df_clean['loan_status'],normalize='index') * 100

loan_status,Charged Off,Current,Default,Fully Paid,In Grace Period,Late (16-30 days),Late (31-120 days)
high_dti_risk,,,,,,,
0,14.730519,9.612288,0.000000,75.027590,0.189966,0.057894,0.381742
1,21.151092,13.623344,0.002238,64.422216,0.210347,0.076083,0.514680

In [43]:
#created multi risk indicator
df_clean.loc[:, 'total_risk_score'] = (df_clean['high_util_risk'] + df_clean['high_dti_risk'])

In [44]:
df_clean['total_risk_score'].value_counts()

total_risk_score
1    46121
2    31582
0    22258
Name: count, dtype: int64

In [45]:
pd.crosstab(df_clean['total_risk_score'],df_clean['loan_status'],normalize='index') * 100

loan_status,Charged Off,Current,Default,Fully Paid,In Grace Period,Late (16-30 days),Late (31-120 days)
total_risk_score,,,,,,,
0,13.626561,6.927846,0.000000,78.888490,0.130290,0.067391,0.359421
1,16.810130,10.895254,0.000000,71.644153,0.210316,0.058542,0.381605
2,21.556583,15.306187,0.003166,62.241150,0.231144,0.075993,0.585777

In [46]:
df_clean.shape

(99961, 20)

In [47]:
#higher scores correspond to worse loan outcomes.
#As risk score is increasing , charged off increase , fully paid decreased, late loan payers increase.

RELATIONAL DATABASE DESIGN

In [48]:
df_clean.head()

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,annual_inc,loan_status,dti,fico_range_low,fico_range_high,revol_util,pub_rec_bankruptcies,purpose,addr_state,utilization_diff,high_util_risk,high_dti_risk,total_risk_score
0,68407277,3600.0,36 months,13.99,123.03,C,C4,55000.0,Fully Paid,5.91,675.0,679.0,29.7,0.0,debt_consolidation,PA,17.7,0,0,0
1,68355089,24700.0,36 months,11.99,820.28,C,C1,65000.0,Fully Paid,16.06,715.0,719.0,19.2,0.0,small_business,SD,7.2,0,0,0
2,68341763,20000.0,60 months,10.78,432.66,B,B4,63000.0,Fully Paid,10.78,695.0,699.0,56.2,0.0,home_improvement,IL,44.2,1,0,1
3,66310712,35000.0,60 months,14.85,829.90,C,C5,110000.0,Current,17.06,785.0,789.0,11.6,0.0,debt_consolidation,NJ,-0.4,0,0,0
4,68476807,10400.0,60 months,22.45,289.91,F,F1,104433.0,Fully Paid,25.37,695.0,699.0,64.5,0.0,major_purchase,PA,52.5,1,1,2

In [49]:
len(df_clean)

99961

In [53]:
df_clean.columns

Index(['id', 'loan_amnt', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'annual_inc', 'loan_status', 'dti', 'fico_range_low',
       'fico_range_high', 'revol_util', 'pub_rec_bankruptcies', 'purpose',
       'addr_state', 'utilization_diff', 'high_util_risk', 'high_dti_risk',
       'total_risk_score'],
      dtype='object')

In [54]:
customers_df = df_clean[[
    'id',
    'annual_inc',
    'fico_range_low',
    'fico_range_high',
    'pub_rec_bankruptcies',
    'addr_state',
    'dti'
]]

In [55]:
customers_df.head()

,id,annual_inc,fico_range_low,fico_range_high,pub_rec_bankruptcies,addr_state,dti
0,68407277,55000.0,675.0,679.0,0.0,PA,5.91
1,68355089,65000.0,715.0,719.0,0.0,SD,16.06
2,68341763,63000.0,695.0,699.0,0.0,IL,10.78
3,66310712,110000.0,785.0,789.0,0.0,NJ,17.06
4,68476807,104433.0,695.0,699.0,0.0,PA,25.37

In [56]:
loans_df = df_clean[[
    'id',
    'loan_amnt',
    'term',
    'int_rate',
    'installment',
    'grade',
    'sub_grade',
    'loan_status',
    'purpose'
]]

In [57]:
loans_df.head()

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,loan_status,purpose
0,68407277,3600.0,36 months,13.99,123.03,C,C4,Fully Paid,debt_consolidation
1,68355089,24700.0,36 months,11.99,820.28,C,C1,Fully Paid,small_business
2,68341763,20000.0,60 months,10.78,432.66,B,B4,Fully Paid,home_improvement
3,66310712,35000.0,60 months,14.85,829.90,C,C5,Current,debt_consolidation
4,68476807,10400.0,60 months,22.45,289.91,F,F1,Fully Paid,major_purchase

In [58]:
customers_df['id'].is_unique #since customer_id will act as primary key , every customer has a unique identifier.

True

In [59]:
#checking relationship consistency
loans_df['id'].isin(customers_df['id']).all()

True

In [60]:
#That means: every loan is correctly linked to a customer.
#This is called:referential integrity.

- primary key
- relational tables
- referential integrity

These are: core database architecture concepts.

In [61]:
merged_df = customers_df.merge(loans_df,on='id',how='inner') #relational join operation

In [62]:
merged_df.head()

,id,annual_inc,fico_range_low,fico_range_high,pub_rec_bankruptcies,addr_state,dti,loan_amnt,term,int_rate,installment,grade,sub_grade,loan_status,purpose
0,68407277,55000.0,675.0,679.0,0.0,PA,5.91,3600.0,36 months,13.99,123.03,C,C4,Fully Paid,debt_consolidation
1,68355089,65000.0,715.0,719.0,0.0,SD,16.06,24700.0,36 months,11.99,820.28,C,C1,Fully Paid,small_business
2,68341763,63000.0,695.0,699.0,0.0,IL,10.78,20000.0,60 months,10.78,432.66,B,B4,Fully Paid,home_improvement
3,66310712,110000.0,785.0,789.0,0.0,NJ,17.06,35000.0,60 months,14.85,829.90,C,C5,Current,debt_consolidation
4,68476807,104433.0,695.0,699.0,0.0,PA,25.37,10400.0,60 months,22.45,289.91,F,F1,Fully Paid,major_purchase

Instead of: one giant messy table,

we create:
- specialized tables
- then combine them when needed.

That gives:
- scalability
- cleaner architecture
- better analytics
- efficient storage

Help answering analytical business questions.

Example:

“Do low FICO customers take higher-interest loans?”

OR

“Do high DTI borrowers have more charge-offs?”

OR

“Which states show riskier loan portfolios?”

In [63]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\preetika\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: psycopg2-binary in c:\users\preetika\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\preetika\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\preetika\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

SQLAlchemy is a Python library used for:

- connecting to databases
- writing SQL operations in Python
- moving DataFrames into SQL
- reading SQL tables into Pandas

psycopg2-binary- This is the PostgreSQL driver.

Python alone cannot directly “talk” to PostgreSQL.
psycopg2 acts like the translator/connector.

FLOW - Pandas  →  SQLAlchemy  →  psycopg2  →  PostgreSQL

In [64]:
from sqlalchemy import create_engine

What is create_engine?- It creates a connection object between Python and a database.

Think of it like:
Python  ←→  Engine/Connector  ←→  PostgreSQL

In [65]:
engine = create_engine(
    'postgresql://postgres:preetika123@localhost:5432/credit_risk_db'
)

In [66]:
customers_df.to_sql(
    'customers',
    engine,
    if_exists='replace',
    index=False
)

961

In [67]:
loans_df.to_sql(
    'loans',
    engine,
    if_exists='replace',
    index=False
)

961